version: "3"

services:
  db:
    image: mysql:8.0
    container_name: soukai-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=${APP_DATABASE_USERNAME}
      - MYSQL_PASSWORD=${APP_DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${APP_DATABASE_PASSWORD}
      - MYSQL_DATABASE=${APP_DATABASE}
    volumes:
      - db-cache:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    image: soukai-rails
    container_name: soukai-rails
    ports:
      - "${PORT}:3000"
    volumes:
      - "./:/myapp"
    command: /bin/sh -c "bundle exec rails server -b '0.0.0.0' -p ${PORT:-3000} -e ${RAILS_ENV}"
    depends_on:
      - db

  # nginx:
  #   image: nginx:1.21.6
  #   container_name: soukai-app
  #   volumes:
  #     - ./resources/secrets/nginx/conf.d:/etc/nginx/conf.d
  #     - ./public:/var/www/project/public
  #   restart: always
  #   ports:
  #     - "8083:80"
  #   links:
  #     - app

volumes:
  db-cache:
